http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https # Redirige todo el tráfico HTTP a HTTPS                                                    
        permanent: true                                                                                          
  routers:
    example-http:    
      rule: "Host(<example.com>)"
      service: go-service
      entrypoints:      
        - web           
      middlewares:      
        - https-redirect
    example-https:
      rule: "Host(<example.com>)"
      service: go-service
      entrypoints:
        - websecure
      tls:
        certResolver: myresolver
  services:
    example-service:
      loadBalancer:
        servers:
          - url: "http://10.0.0.2:80/"
